# Generated by Django 4.1.4 on 2023-01-12 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'city',
            },
        ),
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('status', models.BooleanField(blank=True, default=True)),
            ],
            options={
                'db_table': 'job_category',
            },
        ),
        migrations.CreateModel(
            name='JobVacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation_name', models.CharField(blank=True, max_length=200, null=True)),
                ('organisation_logo', models.ImageField(blank=True, null=True, upload_to='organisation_logo/')),
                ('role', models.CharField(blank=True, max_length=200, null=True)),
                ('functional_area', models.CharField(blank=True, max_length=200, null=True)),
                ('industry_type', models.CharField(blank=True, max_length=200, null=True)),
                ('qualification', models.CharField(blank=True, max_length=200, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('experience', models.CharField(blank=True, max_length=200, null=True)),
                ('perks_and_benifits', models.CharField(blank=True, max_length=200, null=True)),
                ('skills', models.TextField(blank=True, null=True)),
                ('duties', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'pending'), ('APPROVED', 'approved'), ('EXPIRED', 'expired'), ('DELETED', 'deleted')], default='pending', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('salary', models.FloatField(blank=True, default=0.0)),
                ('max_salary', models.FloatField(blank=True, default=0.0)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_part_time', models.BooleanField(default=False)),
                ('source_link', models.CharField(blank=True, max_length=250, null=True)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('out_source', models.BooleanField(blank=True, default=False)),
                ('tag', models.TextField(blank=True, null=True)),
                ('is_amount_disclose', models.BooleanField(default=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job.city')),
                ('job_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job.jobcategory')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'job_vacancy',
            },
        ),
        migrations.CreateModel(
            name='JobApply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='job.jobvacancy')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'job_apply',
            },
        ),
    ]
