# Generated by Django 4.1.3 on 2022-11-19 18:08

from django.db import migrations


def load_roles(apps, schema_editor):
    Role = apps.get_model("users", "Role")

    role_superadmin = Role(id=1, name='IS_SUPERADMIN')
    role_superadmin.save()

    role_admin = Role(id=2, name='IS_ADMIN')
    role_admin.save()

    role_job_seeker = Role(id=3, name='IS_JOB_SEEKER')
    role_job_seeker.save()

    role_organisation = Role(id=4, name='IS_ORGANISATION')
    role_organisation.save()


def delete_roles(apps, schema_editor):
    Role = apps.get_model("users", "Role")
    Role.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_roles, delete_roles),

    ]
