# Generated by Django 3.2.6 on 2023-05-17 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20221119_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.PositiveSmallIntegerField(choices=[(1, 'is_superadmin'), (2, 'is_admin'), (3, 'is_student'), (4, 'is_professional'), (5, 'is_organisation')], primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(blank=True, choices=[('IS_SUPERADMIN', 'is_superadmin'), ('IS_ADMIN', 'is_admin'), ('IS_STUDENT', 'is_student'), ('IS_PROFESSIONAL', 'is_professional'), ('IS_ORGANISATION', 'is_organisation')], max_length=100, null=True),
        ),
    ]
