# Generated by Django 3.2.6 on 2023-05-17 06:17

from django.db import migrations


def load_roles(apps, schema_editor):
    Role = apps.get_model("users", "Role")

    role_superadmin = Role(id=1, name='IS_SUPERADMIN')
    role_superadmin.save()

    role_admin = Role(id=2, name='IS_ADMIN')
    role_admin.save()

    role_owner = Role(id=3, name='IS_STUDENT')
    role_owner.save()

    role_owner = Role(id=4, name='IS_PROFESSIONAL')
    role_owner.save()

    role_owner = Role(id=5, name='IS_ORGANISATION')
    role_owner.save()


def delete_roles(apps, schema_editor):
    Role = apps.get_model("users", "Role")
    Role.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20230517_1135'),
    ]

    operations = [
        migrations.RunPython(load_roles, delete_roles),
    ]
